# Generated by Django 4.2 on 2023-07-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_remove_user_model_key_remove_user_model_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='title',
        ),
    ]
